### ISSUE TITLE
Is there any performance or negative impacts?

### ISSUE THREAD

**Issue by indivisable** [kyle-ssg/react-native-globals#1]
Is there any drawbacks with using this such as performance or code bloat?

**Comment by kyle-ssg** [comment]
I guess it'd be worth testing out that theory, perhaps on the out of box react native app but my strong suggestion would be no to both. Here's my reasoning behind this:

In the literal sense this would reduce "code bloat" in your app, though if you're talking about memory allocation I guess you could benchmark it though I think we'd be looking at little to no difference.

Performance again, I think technically speaking you'd already be importing all these modules the moment you do a require('react-native'). This can be seen in ```node_modules/react-native/Libraries/react-native/react-native.js``` , the only thing you're actually doing here is declaring a pointer to it.

The only negative impact I can see with this module (so far) is based on how you use it. If you think your module could be shared across multiple projects you should probably require react-native stuff in a usual way, that way you can copy it between projects without having to worry about this module. This is what I mean by **Project specific components** in the readme.

I'd be interested to hear other people's opinions on this though, specifically around performance.

**Comment by indivisable** [comment]
@kyle-ssg thanks, I'll try and do some tests but yes I agree I see this more for development/prototyping in regards to using to import all the RN classes. But it is really convenient way to automatically include any global classes used in project, which can be a pain at times. 

I'll keep testing in my project and see if memory goes up or size of output bundle.

Cheers!

**Comment by kyle-ssg** [comment]
Look forward to hearing the results 👍 !

Cheers
